//! A count track read as a **displacement** of the base track.
//!
//! The base track (spliced counts) alone places every unit and trains the
//! gene features; a displaced track (unspliced counts) is generated by the
//! SAME gene features at a moved position, with its own gene biases:
//!
//! ```text
//! P(g | u, base)      = softmax_g( ⟨θ_u,       ρ_g⟩ + b_g )
//! P(g | u, displaced) = softmax_g( ⟨θ_u + d_u, ρ_g⟩ + b'_g )
//! ```
//!
//! `d_u` is the unit's displacement: where its displaced profile sits in the
//! base track's space. It is learned by two classification rules, drawn at
//! random per step (`rule_a_prob`):
//!
//! - **rule A, which gene**: a displaced read is classified among the unit's
//!   genes, the softmax above (base tables frozen, `θ_u` frozen);
//! - **rule B, which track**: a read of `(u, g)` is classified as displaced
//!   or base, `σ(κ_u + (b'_g − b_g) + ⟨d_u, ρ_g⟩)`, the spliced reads of the
//!   same gene and unit being the negatives.
//!
//! Neither rule reaches `θ`, `ρ` or `b`: they are read as constants, so the
//! displaced track cannot move the base space, whatever its depth. The
//! expected gradient of the alternation is that of `p·L_A + (1 − p)·L_B`, so
//! the displaced counts enter once.
//!
//! Two stages, as the base fit has:
//! 1. **pseudobulks**: a free `d_p`, `κ_p` per pseudobulk of every level, and
//!    the gene biases `b'`, ridge `‖d_p‖²` toward no displacement;
//! 2. **cells**: an encoder reads a cell's displaced counts through the frozen
//!    gene table and gives `(d_c, κ_c)`; distilled onto the cell's finest
//!    pseudobulk's `d_p`, then refined on the cell's own counts with the same
//!    two rules, ridge `‖d_c − d_{p(c)}‖²`. A seeded tenth of the cells is held
//!    out and scored.

use crate::data::UnifiedData;
use crate::fit::config::TrackSpec;
use crate::progress::new_progress_bar;
use anyhow::Context;
use legume_numeric::candle::candle_core::{DType, Device, Tensor, Var};
use legume_numeric::candle::candle_nn::{AdamW, Optimizer, ParamsAdamW, VarBuilder, VarMap};
use legume_numeric::candle::encoder::{PooledGeneEncoder, PooledGeneEncoderArgs};
use legume_numeric::candle::feature_embedding::FeatureEmbedding;
use legume_numeric::candle::grad_clip::clipped_backward_step;
use legume_numeric::candle::loss::multinomial_nll_profiled;
use legume_numeric::matrix::rand_util::mix_seed;
use log::info;
use nalgebra::DMatrix;
use rand::rngs::StdRng;
use rand::seq::SliceRandom;
use rand::{RngExt, SeedableRng};
use rayon::prelude::*;

/// Width of the encoder trunk, as phase 2's.
const TRUNK_WIDTH: usize = 128;
/// Units per optimizer step.
const UNITS_PER_STEP: usize = 128;
const GRAD_CLIP: f64 = 5.0;
/// Share of cells held out of the encoder's training and scored.
const HOLDOUT_FRACTION: f64 = 0.1;
/// The var-name prefix the encoder is saved under.
const VAR_PREFIX: &str = "displaced_enc";
/// The per-gene mean's tensor name inside the saved file.
const MEAN_TENSOR: &str = "displaced_enc.feature_mean";
/// Sub-stream tags for this module's seeds.
const SEED_PB: u64 = 0x4449_5350_5042;
const SEED_CELL: u64 = 0x4449_5350_4345;

///////////////////
// Axis and knobs //
///////////////////

/// Where the base and the displaced counts of every gene of the live (base)
/// axis are in the count backend, after [`split_displaced`] cut the axis down
/// to the base track.
#[derive(Clone, Debug)]
pub struct DisplacedAxis {
    /// Per live row (gene): the backend row of its base-track counts.
    pub base_backend_row: Vec<u32>,
    /// Per live row (gene): the backend row of its displaced-track counts,
    /// `u32::MAX` for a gene the displaced track has no row for.
    pub displaced_backend_row: Vec<u32>,
    /// The displaced track's name, e.g. `count/unspliced`.
    pub track_name: Box<str>,
}

impl DisplacedAxis {
    /// Live rows carrying a displaced row, ascending: the displaced support.
    #[must_use]
    pub fn support(&self) -> Vec<u32> {
        self.displaced_backend_row
            .iter()
            .enumerate()
            .filter(|&(_, &r)| r != u32::MAX)
            .map(|(g, _)| g as u32)
            .collect()
    }
}

/// How the displaced track is learned. See the module docs.
#[derive(Clone, Debug)]
pub struct DisplacedTrackConfig {
    pub axis: DisplacedAxis,
    /// Probability a step uses rule A (which gene) rather than rule B (which
    /// track). `1` is rule A only, `0` rule B only.
    pub rule_a_prob: f64,
    /// Ridge precision on a pseudobulk's displacement (`1/σ²`).
    pub l2_pb: f32,
    /// Ridge precision of a cell's displacement around its pseudobulk's
    /// (`1/τ²`).
    pub l2_cell: f32,
    /// Passes over the pseudobulks.
    pub pb_epochs: usize,
    /// Passes over the cells distilling the encoder onto the pseudobulks.
    pub distill_epochs: usize,
    /// Passes over the cells refining the encoder on their own counts.
    pub refine_epochs: usize,
    pub learning_rate: f64,
}

impl DisplacedTrackConfig {
    /// The default knobs on `axis`.
    #[must_use]
    pub fn new(axis: DisplacedAxis) -> Self {
        Self {
            axis,
            rule_a_prob: 0.5,
            l2_pb: 1.0,
            l2_cell: 1.0,
            pb_epochs: 50,
            distill_epochs: 20,
            refine_epochs: 10,
            learning_rate: 1e-2,
        }
    }
}

/// Cut `unified` down to the base track's rows and say where track
/// `displaced`'s counts are. Call before building the fit's other per-feature
/// inputs (they then index the base axis), and fit with no track spec.
///
/// Requires two tracks, the base and `displaced`, both count tracks, and a
/// base row for every gene. The live axis is the base rows in ascending row
/// order; its names are the base rows' names.
pub fn split_displaced(
    unified: &mut UnifiedData,
    tracks: &TrackSpec,
    displaced: usize,
) -> anyhow::Result<DisplacedAxis> {
    tracks.validate(unified.n_features())?;
    anyhow::ensure!(
        tracks.n_tracks() == 2 && displaced == 1,
        "a displaced track needs exactly the base track and one other (got {} tracks, displaced {displaced})",
        tracks.n_tracks()
    );
    anyhow::ensure!(
        tracks.tracks[displaced].is_count,
        "the displaced track `{}` is not a count track",
        tracks.tracks[displaced].name
    );
    let n_genes = tracks.n_genes();
    let base_rows = tracks.rows_of_track(0);
    anyhow::ensure!(
        base_rows.len() == n_genes,
        "every gene needs a base-track row: {} genes, {} base rows",
        n_genes,
        base_rows.len()
    );
    let backend = &unified.feature_to_backend_row;
    // gene → backend row of its displaced row.
    let mut displaced_of_gene = vec![u32::MAX; n_genes];
    for row in tracks.rows_of_track(displaced) {
        let g = tracks.gene_of_row[row as usize] as usize;
        displaced_of_gene[g] = backend[row as usize] as u32;
    }
    let base_backend_row: Vec<u32> = base_rows
        .iter()
        .map(|&row| backend[row as usize] as u32)
        .collect();
    let displaced_backend_row: Vec<u32> = base_rows
        .iter()
        .map(|&row| displaced_of_gene[tracks.gene_of_row[row as usize] as usize])
        .collect();
    let keep: Vec<usize> = base_rows.iter().map(|&r| r as usize).collect();
    unified.subset_features(&keep);
    Ok(DisplacedAxis {
        base_backend_row,
        displaced_backend_row,
        track_name: tracks.tracks[displaced].name.clone(),
    })
}

/////////////
// Results //
/////////////

/// What the displaced track's fit gives back.
pub struct DisplacementOutput {
    pub track_name: Box<str>,
    /// Live rows of the displaced support, ascending: the genes `b_displaced`
    /// and every `d · ρ` readout index.
    pub genes: Vec<u32>,
    /// Per support gene, the displaced track's bias `b'_g`.
    pub b_displaced: Vec<f32>,
    /// Per support gene, the base track's bias `b_g` (in the cells' frame).
    pub b_base: Vec<f32>,
    /// Per level (coarsest → finest), `[n_pb × H]` pseudobulk displacements.
    pub d_pb: Vec<DMatrix<f32>>,
    /// Per level, each pseudobulk's rule-B intercept `κ_p`.
    pub kappa_pb: Vec<Vec<f32>>,
    /// `[n_cells × H]` cell displacements.
    pub d_cell: DMatrix<f32>,
    /// Each cell's rule-B intercept `κ_c`.
    pub kappa_cell: Vec<f32>,
    /// The cell encoder, for placing new cells' displaced counts.
    pub encoder: DisplacementEncoder,
    pub held_out: HeldOutScore,
}

/// Held-out cells' displaced counts under rule A, with each cell's
/// displacement against none.
#[derive(Clone, Debug, Default)]
pub struct HeldOutScore {
    pub n_cells: usize,
    pub n_counts: f64,
    /// Log-likelihood gain per displaced count of `d_c` over `d = 0`.
    pub gain_per_count: f64,
}

//////////////////////
// Host-side inputs //
//////////////////////

/// One unit's counts on the displaced support: local gene ids and counts, for
/// the base and the displaced track.
#[derive(Clone, Debug, Default)]
pub(crate) struct UnitCounts {
    pub base: Vec<(u32, f32)>,
    pub displaced: Vec<(u32, f32)>,
}

impl UnitCounts {
    fn displaced_total(&self) -> f32 {
        self.displaced.iter().map(|&(_, c)| c).sum()
    }

    fn is_empty(&self) -> bool {
        self.base.is_empty() && self.displaced.is_empty()
    }
}

/// The frozen base tables on the displaced support.
pub(crate) struct Frozen {
    /// `[S × H]` row-major gene rows ρ.
    pub rho: Vec<f32>,
    /// `[S]` base biases b.
    pub b: Vec<f32>,
    pub h: usize,
}

impl Frozen {
    fn s(&self) -> usize {
        self.b.len()
    }
}

/// Sum `rows`' counts per group: `groups[p]` lists the members of group `p`.
pub(crate) fn sum_groups(rows: &[UnitCounts], groups: &[Vec<usize>]) -> Vec<UnitCounts> {
    groups
        .par_iter()
        .map(|members| {
            let mut base: rustc_hash::FxHashMap<u32, f32> = Default::default();
            let mut disp: rustc_hash::FxHashMap<u32, f32> = Default::default();
            for &c in members {
                for &(g, v) in &rows[c].base {
                    *base.entry(g).or_default() += v;
                }
                for &(g, v) in &rows[c].displaced {
                    *disp.entry(g).or_default() += v;
                }
            }
            let mut base: Vec<(u32, f32)> = base.into_iter().collect();
            let mut displaced: Vec<(u32, f32)> = disp.into_iter().collect();
            base.sort_unstable_by_key(|&(g, _)| g);
            displaced.sort_unstable_by_key(|&(g, _)| g);
            UnitCounts { base, displaced }
        })
        .collect()
}

/// Dense `[n × s]` base and displaced blocks of `units`, and the displaced
/// totals.
fn dense_block(units: &[&UnitCounts], s: usize) -> (Vec<f32>, Vec<f32>, Vec<f32>) {
    let n = units.len();
    let mut xb = vec![0f32; n * s];
    let mut xd = vec![0f32; n * s];
    xb.par_chunks_mut(s)
        .zip(xd.par_chunks_mut(s))
        .zip(units.par_iter())
        .for_each(|((b, d), u)| {
            for &(g, v) in &u.base {
                b[g as usize] = v;
            }
            for &(g, v) in &u.displaced {
                d[g as usize] = v;
            }
        });
    let totals = units.iter().map(|u| u.displaced_total()).collect();
    (xb, xd, totals)
}

/////////////////////
// The two rules   //
/////////////////////

/// The device-side frozen tables.
struct DeviceTables {
    /// `[H × S]`, ρ transposed, for `θ · ρᵀ`.
    rho_t: Tensor,
    /// `[1 × S]` base biases.
    b: Tensor,
}

impl DeviceTables {
    fn new(frozen: &Frozen, dev: &Device) -> anyhow::Result<Self> {
        let s = frozen.s();
        let rho = Tensor::from_slice(&frozen.rho, (s, frozen.h), dev)?;
        Ok(Self {
            rho_t: rho.t()?.contiguous()?,
            b: Tensor::from_slice(&frozen.b, (1, s), dev)?,
        })
    }
}

/// One step's per-unit loss, `[n]`, for the rule drawn: rule A when
/// `rule_a`, else rule B. `theta`, `d` are `[n × H]`; `kappa` `[n]`;
/// `b_disp` `[1 × S]`; `xb`, `xd` `[n × S]`; `nd` `[n]` the displaced totals.
#[allow(clippy::too_many_arguments)]
fn rule_loss(
    rule_a: bool,
    tables: &DeviceTables,
    theta: &Tensor,
    d: &Tensor,
    kappa: &Tensor,
    b_disp: &Tensor,
    xb: &Tensor,
    xd: &Tensor,
    nd: &Tensor,
) -> anyhow::Result<Tensor> {
    if rule_a {
        // Which gene: the displaced read among the unit's genes, at θ + d.
        let s = (theta + d)?.matmul(&tables.rho_t)?.broadcast_add(b_disp)?;
        Ok(multinomial_nll_profiled(xd, &s, nd)?)
    } else {
        // Which track: σ(κ + (b' − b) + ⟨d, ρ⟩); displaced reads positive,
        // base reads of the same (unit, gene) negative.
        let logit = d
            .matmul(&tables.rho_t)?
            .broadcast_add(&(b_disp - &tables.b)?)?
            .broadcast_add(&kappa.unsqueeze(1)?)?;
        let pos = (xd * softplus(&logit.neg()?)?)?;
        let neg = (xb * softplus(&logit)?)?;
        Ok((pos + neg)?.sum(1)?)
    }
}

/// `ln(1 + eˣ)`, stable: `max(x, 0) + ln(1 + e^{−|x|})`.
fn softplus(x: &Tensor) -> anyhow::Result<Tensor> {
    let tail = (x.abs()?.neg()?.exp()? + 1.0)?.log()?;
    Ok((x.relu()? + tail)?)
}

/// `[n]` rule-A log-likelihood (up to the count-only constant) of `xd` at
/// position `pos` with displaced biases `b_disp`.
fn rule_a_loglik(
    tables: &DeviceTables,
    pos: &Tensor,
    b_disp: &Tensor,
    xd: &Tensor,
    nd: &Tensor,
) -> anyhow::Result<Tensor> {
    let s = pos.matmul(&tables.rho_t)?.broadcast_add(b_disp)?;
    Ok(multinomial_nll_profiled(xd, &s, nd)?.neg()?)
}

///////////////////////////////
// Stage 1: the pseudobulks  //
///////////////////////////////

/// The pseudobulks' fit: `d` and `κ` per unit, and the displaced biases.
pub(crate) struct PbFit {
    /// `[n_units × H]`.
    pub d: DMatrix<f32>,
    pub kappa: Vec<f32>,
    /// `[S]`.
    pub b_displaced: Vec<f32>,
}

/// Fit `d_p`, `κ_p` and `b'` on the pseudobulks: `theta` is `[n_units × H]`
/// (frozen), `units` their counts on the support.
pub(crate) fn fit_pseudobulks(
    frozen: &Frozen,
    theta: &DMatrix<f32>,
    units: &[UnitCounts],
    knobs: &DisplacedTrackConfig,
    seed: u64,
    dev: &Device,
) -> anyhow::Result<PbFit> {
    let (n, h, s) = (units.len(), frozen.h, frozen.s());
    anyhow::ensure!(
        theta.nrows() == n && theta.ncols() == h,
        "θ is not [units × H]"
    );
    let tables = DeviceTables::new(frozen, dev)?;
    let theta_t = to_device(theta, dev)?;
    let d = Var::zeros((n, h), DType::F32, dev)?;
    let kappa = Var::zeros(n, DType::F32, dev)?;
    let b_disp = Var::from_tensor(&tables.b)?;
    let mut adam = AdamW::new(
        vec![d.clone(), kappa.clone(), b_disp.clone()],
        ParamsAdamW {
            lr: knobs.learning_rate,
            weight_decay: 0.0,
            ..Default::default()
        },
    )?;
    let mut order: Vec<usize> = (0..n).filter(|&u| !units[u].is_empty()).collect();
    let mut rng = StdRng::seed_from_u64(mix_seed(seed, SEED_PB));
    let half_l2 = f64::from(knobs.l2_pb) / 2.0;
    info!(
        "Displaced track — fitting {} pseudobulks' displacements over {s} genes: {} epochs, rule A \
         with probability {:.2}, ridge {}",
        order.len(),
        knobs.pb_epochs,
        knobs.rule_a_prob,
        knobs.l2_pb
    );
    let bar = new_progress_bar(knobs.pb_epochs as u64);
    for _ in 0..knobs.pb_epochs {
        order.shuffle(&mut rng);
        for chunk in order.chunks(UNITS_PER_STEP) {
            let rows: Vec<&UnitCounts> = chunk.iter().map(|&u| &units[u]).collect();
            let (xb, xd, nd) = dense_block(&rows, s);
            let m = chunk.len();
            let idx = Tensor::from_vec(chunk.iter().map(|&u| u as u32).collect(), m, dev)?;
            let xb = Tensor::from_vec(xb, (m, s), dev)?;
            let xd = Tensor::from_vec(xd, (m, s), dev)?;
            let nd = Tensor::from_vec(nd, m, dev)?;
            let th = theta_t.index_select(&idx, 0)?;
            let dd = d.as_tensor().index_select(&idx, 0)?;
            let kk = kappa.as_tensor().index_select(&idx, 0)?;
            let rule_a = rng.random::<f64>() < knobs.rule_a_prob;
            let fit = rule_loss(
                rule_a,
                &tables,
                &th,
                &dd,
                &kk,
                b_disp.as_tensor(),
                &xb,
                &xd,
                &nd,
            )?;
            let ridge = dd.sqr()?.sum(1)?.affine(half_l2, 0.0)?;
            let loss = (fit + ridge)?.mean_all()?;
            clipped_backward_step(&mut adam, &loss, GRAD_CLIP)?;
        }
        bar.inc(1);
    }
    bar.finish_and_clear();
    Ok(PbFit {
        d: from_device(d.as_tensor())?,
        kappa: kappa.as_tensor().to_vec1()?,
        b_displaced: b_disp.as_tensor().flatten_all()?.to_vec1()?,
    })
}

/////////////////////////////////
// Stage 2: the cells' encoder //
/////////////////////////////////

/// The trained cell encoder: reads displaced counts on the support, through
/// the frozen gene table, and gives `[d, κ]`.
pub struct DisplacementEncoder {
    encoder: PooledGeneEncoder,
    varmap: VarMap,
    mean_1d: Tensor,
    h: usize,
}

impl DisplacementEncoder {
    fn build(frozen: &Frozen, mean_1d: &[f32], dev: &Device) -> anyhow::Result<Self> {
        let rho = Tensor::from_slice(&frozen.rho, (frozen.s(), frozen.h), dev)?;
        let varmap = VarMap::new();
        let vb = VarBuilder::from_varmap(&varmap, DType::F32, dev);
        let encoder = PooledGeneEncoder::new(
            FeatureEmbedding::fixed(rho),
            PooledGeneEncoderArgs {
                layers: &[TRUNK_WIDTH],
                out_dim: frozen.h + 1,
                attn_pool: true,
                in_dim_extra: 0,
            },
            &varmap,
            vb.pp(VAR_PREFIX),
        )?;
        let mean_1d = Tensor::from_slice(mean_1d, (1, frozen.s()), dev)?;
        Ok(Self {
            encoder,
            varmap,
            mean_1d,
            h: frozen.h,
        })
    }

    /// `(d [n × H], κ [n])` for dense displaced counts `x [n × S]`.
    fn forward(&self, x: &Tensor, train: bool) -> anyhow::Result<(Tensor, Tensor)> {
        let z = self
            .encoder
            .forward(x, None, Some(&self.mean_1d), None, train)?;
        let d = z.narrow(1, 0, self.h)?;
        let kappa = z.narrow(1, self.h, 1)?.squeeze(1)?;
        Ok((d, kappa))
    }

    /// Save the trunk and the per-gene mean as safetensors at `path`.
    pub fn save(&self, path: &str) -> anyhow::Result<()> {
        let mut tensors: std::collections::HashMap<String, Tensor> = self
            .varmap
            .data()
            .lock()
            .unwrap()
            .iter()
            .map(|(name, var)| (name.clone(), var.as_tensor().clone()))
            .collect();
        tensors.insert(MEAN_TENSOR.to_string(), self.mean_1d.flatten_all()?);
        legume_numeric::candle::candle_core::safetensors::save(&tensors, path)
            .with_context(|| format!("saving the displaced-track encoder to {path}"))?;
        Ok(())
    }
}

/// The cells' fit.
pub(crate) struct CellFit {
    pub d: DMatrix<f32>,
    pub kappa: Vec<f32>,
    pub encoder: DisplacementEncoder,
    pub held_out: HeldOutScore,
}

/// Train the cell encoder: distil onto `target` (each cell's pseudobulk
/// displacement, `[n × H]`), then refine on the cells' own counts with the two
/// rules, ridge toward `target`. `theta` `[n × H]` frozen; `b_displaced` the
/// stage-1 biases, frozen.
#[allow(clippy::too_many_arguments)]
pub(crate) fn fit_cells(
    frozen: &Frozen,
    theta: &DMatrix<f32>,
    cells: &[UnitCounts],
    target: &DMatrix<f32>,
    b_displaced: &[f32],
    knobs: &DisplacedTrackConfig,
    seed: u64,
    dev: &Device,
) -> anyhow::Result<CellFit> {
    let (n, s) = (cells.len(), frozen.s());
    anyhow::ensure!(
        theta.nrows() == n && target.nrows() == n,
        "θ / target are not [cells × H]"
    );
    let tables = DeviceTables::new(frozen, dev)?;
    let theta_t = to_device(theta, dev)?;
    let target_t = to_device(target, dev)?;
    let b_disp = Tensor::from_slice(b_displaced, (1, s), dev)?;

    // The trunk's gate divides by each gene's mean displaced rate.
    let mut mean = vec![0f64; s];
    for c in cells {
        for &(g, v) in &c.displaced {
            mean[g as usize] += f64::from(v);
        }
    }
    let mean_1d: Vec<f32> = mean
        .iter()
        .map(|&m| ((m / n.max(1) as f64) as f32).max(1e-6))
        .collect();
    let encoder = DisplacementEncoder::build(frozen, &mean_1d, dev)?;

    let mut rng = StdRng::seed_from_u64(mix_seed(seed, SEED_CELL));
    let mut active: Vec<usize> = (0..n).filter(|&c| !cells[c].is_empty()).collect();
    active.shuffle(&mut rng);
    let n_held = ((active.len() as f64) * HOLDOUT_FRACTION).round() as usize;
    let held: Vec<usize> = active[..n_held].to_vec();
    let mut train: Vec<usize> = active[n_held..].to_vec();

    let block = |ids: &[usize]| -> anyhow::Result<(Tensor, Tensor, Tensor, Tensor)> {
        let rows: Vec<&UnitCounts> = ids.iter().map(|&c| &cells[c]).collect();
        let (xb, xd, nd) = dense_block(&rows, s);
        let m = ids.len();
        let idx = Tensor::from_vec(ids.iter().map(|&c| c as u32).collect(), m, dev)?;
        Ok((
            idx,
            Tensor::from_vec(xb, (m, s), dev)?,
            Tensor::from_vec(xd, (m, s), dev)?,
            Tensor::from_vec(nd, m, dev)?,
        ))
    };

    let mut adam = AdamW::new(
        encoder.varmap.all_vars(),
        ParamsAdamW {
            lr: knobs.learning_rate / 10.0,
            weight_decay: 1e-4,
            ..Default::default()
        },
    )?;
    info!(
        "Displaced track — encoding {} cells ({n_held} held out): {} distil + {} refine epochs",
        train.len(),
        knobs.distill_epochs,
        knobs.refine_epochs
    );
    let half_l2 = f64::from(knobs.l2_cell) / 2.0;
    let bar = new_progress_bar((knobs.distill_epochs + knobs.refine_epochs) as u64);
    for epoch in 0..knobs.distill_epochs + knobs.refine_epochs {
        let distil = epoch < knobs.distill_epochs;
        train.shuffle(&mut rng);
        for chunk in train.chunks(UNITS_PER_STEP) {
            let (idx, xb, xd, nd) = block(chunk)?;
            let (d, kappa) = encoder.forward(&xd, true)?;
            let tgt = target_t.index_select(&idx, 0)?;
            let toward = (&d - &tgt)?.sqr()?.sum(1)?;
            let loss = if distil {
                toward.mean_all()?
            } else {
                let th = theta_t.index_select(&idx, 0)?;
                let rule_a = rng.random::<f64>() < knobs.rule_a_prob;
                let fit = rule_loss(rule_a, &tables, &th, &d, &kappa, &b_disp, &xb, &xd, &nd)?;
                (fit + toward.affine(half_l2, 0.0)?)?.mean_all()?
            };
            clipped_backward_step(&mut adam, &loss, GRAD_CLIP)?;
        }
        bar.inc(1);
    }
    bar.finish_and_clear();

    // Every cell through the trained encoder; empty cells keep their target.
    let mut d_all = target.clone();
    let mut kappa_all = vec![0f32; n];
    for chunk in active.chunks(UNITS_PER_STEP) {
        let (_, _, xd, _) = block(chunk)?;
        let (d, kappa) = encoder.forward(&xd, false)?;
        let d = from_device(&d)?;
        let kappa: Vec<f32> = kappa.to_vec1()?;
        for (k, &c) in chunk.iter().enumerate() {
            d_all.row_mut(c).copy_from(&d.row(k));
            kappa_all[c] = kappa[k];
        }
    }

    // Held-out cells: rule-A log-likelihood with their displacement, against
    // none.
    let mut held_out = HeldOutScore {
        n_cells: held.len(),
        ..Default::default()
    };
    let mut gain = 0f64;
    for chunk in held.chunks(UNITS_PER_STEP) {
        let (idx, _, xd, nd) = block(chunk)?;
        let th = theta_t.index_select(&idx, 0)?;
        let d = to_device(&select_rows(&d_all, chunk), dev)?;
        let with = rule_a_loglik(&tables, &(&th + &d)?, &b_disp, &xd, &nd)?;
        let without = rule_a_loglik(&tables, &th, &b_disp, &xd, &nd)?;
        gain += f64::from((with - without)?.sum_all()?.to_scalar::<f32>()?);
        held_out.n_counts += f64::from(nd.sum_all()?.to_scalar::<f32>()?);
    }
    held_out.gain_per_count = gain / held_out.n_counts.max(1.0);
    info!(
        "Displaced track — held-out cells: {:+.4} log-likelihood per displaced count with the \
         displacement ({} cells, {:.0} counts)",
        held_out.gain_per_count, held_out.n_cells, held_out.n_counts
    );
    Ok(CellFit {
        d: d_all,
        kappa: kappa_all,
        encoder,
        held_out,
    })
}

/////////////////////////
// From the fit's data //
/////////////////////////

/// Every cell's base and displaced counts on the support, streamed from the
/// count backend (raw counts). `support` are the live rows; local gene `i` is
/// `support[i]`.
pub(crate) fn read_counts(
    unified: &UnifiedData,
    axis: &DisplacedAxis,
    support: &[u32],
) -> anyhow::Result<Vec<UnitCounts>> {
    let data = unified.count_backend();
    let n_cells = data.num_columns();
    // backend row → (local gene, is displaced).
    let mut role = vec![(u32::MAX, false); data.num_rows()];
    for (i, &g) in support.iter().enumerate() {
        let g = g as usize;
        role[axis.base_backend_row[g] as usize] = (i as u32, false);
        role[axis.displaced_backend_row[g] as usize] = (i as u32, true);
    }
    let mut out: Vec<UnitCounts> = (0..n_cells).map(|_| UnitCounts::default()).collect();
    let chunk = (1usize << 14).min(n_cells.max(1));
    data.for_each_triplet(0..n_cells, chunk, |brow, col, v| {
        if v == 0.0 {
            return;
        }
        let (g, displaced) = role[brow as usize];
        if g == u32::MAX {
            return;
        }
        let cell = &mut out[col as usize];
        if displaced {
            cell.displaced.push((g, v));
        } else {
            cell.base.push((g, v));
        }
    })?;
    Ok(out)
}

/// Fit the displaced track after the base fit: `theta_cell` `[n_cells × H]`,
/// the gene rows `e_feat` `[G × H]` and biases `b_feat` `[G]` in the cells'
/// frame, the pseudobulk tables per level (same frame), and each level's cell
/// membership.
#[allow(clippy::too_many_arguments)]
pub(crate) fn fit_displaced(
    unified: &UnifiedData,
    knobs: &DisplacedTrackConfig,
    theta_cell: &DMatrix<f32>,
    e_feat: &DMatrix<f32>,
    b_feat: &[f32],
    pb_tables: &[&DMatrix<f32>],
    cell_to_pb_per_level: &[Vec<usize>],
    seed: u64,
    dev: &Device,
) -> anyhow::Result<DisplacementOutput> {
    let h = e_feat.ncols();
    let support = knobs.axis.support();
    anyhow::ensure!(
        !support.is_empty(),
        "the displaced track has no rows on the base axis"
    );
    let mut rho = Vec::with_capacity(support.len() * h);
    for &g in &support {
        rho.extend(e_feat.row(g as usize).iter().copied());
    }
    let frozen = Frozen {
        rho,
        b: support.iter().map(|&g| b_feat[g as usize]).collect(),
        h,
    };
    let cells = read_counts(unified, &knobs.axis, &support)?;

    // Every level's pseudobulks, stacked, with their tables.
    let mut pb_counts = Vec::new();
    let mut pb_theta_rows: Vec<f32> = Vec::new();
    let mut level_sizes = Vec::new();
    for (table, c2pb) in pb_tables.iter().zip(cell_to_pb_per_level) {
        let n_pb = table.nrows();
        let mut groups: Vec<Vec<usize>> = vec![Vec::new(); n_pb];
        for (c, &p) in c2pb.iter().enumerate() {
            if p < n_pb {
                groups[p].push(c);
            }
        }
        pb_counts.extend(sum_groups(&cells, &groups));
        for row in table.row_iter() {
            pb_theta_rows.extend(row.iter().copied());
        }
        level_sizes.push(n_pb);
    }
    let pb_theta = DMatrix::from_row_slice(pb_counts.len(), h, &pb_theta_rows);
    let pb = fit_pseudobulks(&frozen, &pb_theta, &pb_counts, knobs, seed, dev)?;

    // Each cell's finest pseudobulk's displacement is its target and centre.
    let finest = cell_to_pb_per_level.last().context("no pseudobulk level")?;
    let finest_offset: usize = level_sizes[..level_sizes.len() - 1].iter().sum();
    let n_finest = *level_sizes.last().expect("a level");
    let mut target = DMatrix::<f32>::zeros(cells.len(), h);
    for (c, &p) in finest.iter().enumerate() {
        if p < n_finest {
            target.row_mut(c).copy_from(&pb.d.row(finest_offset + p));
        }
    }
    let fit = fit_cells(
        &frozen,
        theta_cell,
        &cells,
        &target,
        &pb.b_displaced,
        knobs,
        seed,
        dev,
    )?;

    // Split the stacked pseudobulk rows back per level.
    let mut d_pb = Vec::new();
    let mut kappa_pb = Vec::new();
    let mut at = 0usize;
    for &n in &level_sizes {
        d_pb.push(pb.d.rows(at, n).into_owned());
        kappa_pb.push(pb.kappa[at..at + n].to_vec());
        at += n;
    }
    Ok(DisplacementOutput {
        track_name: knobs.axis.track_name.clone(),
        b_base: frozen.b.clone(),
        genes: support,
        b_displaced: pb.b_displaced,
        d_pb,
        kappa_pb,
        d_cell: fit.d,
        kappa_cell: fit.kappa,
        encoder: fit.encoder,
        held_out: fit.held_out,
    })
}

/////////////
// Helpers //
/////////////

fn to_device(m: &DMatrix<f32>, dev: &Device) -> anyhow::Result<Tensor> {
    let rows: Vec<f32> = m.transpose().as_slice().to_vec();
    Ok(Tensor::from_vec(rows, (m.nrows(), m.ncols()), dev)?)
}

fn from_device(t: &Tensor) -> anyhow::Result<DMatrix<f32>> {
    let (n, h) = t.dims2()?;
    let v: Vec<f32> = t.flatten_all()?.to_vec1()?;
    Ok(DMatrix::from_row_slice(n, h, &v))
}

fn select_rows(m: &DMatrix<f32>, rows: &[usize]) -> DMatrix<f32> {
    DMatrix::from_fn(rows.len(), m.ncols(), |i, k| m[(rows[i], k)])
}

#[cfg(test)]
#[path = "divergence_tests.rs"]
mod divergence_tests;
